name: Build Kora Chain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-feature=-crt-static"
  SOURCE_DATE_EPOCH: 1600000000
  # Additional flags for deterministic builds
  CARGO_PROFILE_RELEASE_DEBUG: 0
  CARGO_PROFILE_PRODUCTION_DEBUG: 0

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build node binary
        run: |
          cargo build --locked --profile production -p kora-chain-node
          # Verify binary was built
          ls -la target/production/kora-chain-node

      - name: Build runtime WASM
        run: |
          cargo build --locked --profile production -p kora-chain-runtime --features on-chain-release-build
          # Verify WASM was built
          ls -la target/production/wbuild/kora-chain-runtime/

      - name: Upload node binary
        uses: actions/upload-artifact@v4
        with:
          name: kora-chain-node
          path: target/production/kora-chain-node
          retention-days: 30

      - name: Upload runtime WASM
        uses: actions/upload-artifact@v4
        with:
          name: kora_chain_runtime.compact.compressed.wasm
          path: target/production/wbuild/kora-chain-runtime/kora_chain_runtime.compact.compressed.wasm
          retention-days: 30

      - name: Generate build checksums
        run: |
          cd target/production
          sha256sum kora-chain-node > kora-chain-node.sha256
          cd wbuild/kora-chain-runtime
          sha256sum kora_chain_runtime.compact.compressed.wasm > kora_chain_runtime.compact.compressed.wasm.sha256

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: |
            target/production/kora-chain-node.sha256
            target/production/wbuild/kora-chain-runtime/kora_chain_runtime.compact.compressed.wasm.sha256
          retention-days: 30

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            RUSTFLAGS=-C target-feature=-crt-static
            SOURCE_DATE_EPOCH=1600000000

      - name: Generate artifact attestation
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true